project:
  type: website
  output-dir: "."

website:
  title: "ZKA"
  navbar:
    title: " "
    left:
      - href: index.qmd
        icon: house
        text: "ZKA"
      - href: about.qmd
        text: About me
      - href: cv/publications.html
        text: Publications
    right:
      - text: "{{< iconify fa6-solid at title='E-mail' width=19px >}}"
        href: mailto:contact@zheer.dk
      - text: "{{< iconify fa6-brands square-github title='GitHub' width=19px >}}"
        href: https://github.com/zheer-kejlberg
      - text: "{{< iconify fa6-brands google-scholar title='Google Scholar' width=19px >}}"
        href: https://scholar.google.com/citations?user=Pr1jGNwAAAAJ&hl=en
      - text: "{{< iconify fa6-brands orcid title='Orcid' width=19px >}}"
        href: https://orcid.org/0000-0003-1201-199X
      - text: "{{< iconify fa6-brands linkedin title='LinkedIn' width=19px >}}"
        href: https://www.linkedin.com/in/zheer-kejlberg/
      - text: "{{< iconify fa6-brands square-bluesky title='Bluesky' width=19px >}}"
        href: https://bsky.app/profile/zheer.bsky.social
      - text: "{{< iconify fa6-brands mastodon title='Mastodon' width=19px >}}"
        href: https://mathstodon.xyz/@zheer_kejlberg
      - text: "{{< iconify fa6-brands square-twitter title='Twitter' width=19px >}}"
        href: https://x.com/zheer_kejlberg

format:
  html:
    theme: darkly
    toc: true