project:
  type: website
  output-dir: "."

website:
  title: "ZKA"
  navbar:
    title: " "
    left:
      - href: index.qmd
        icon: house
        text: "ZKA"
      - href: about.qmd
        text: About me
      - text: Curriculum vitae
        menu:
          - href: cv/cv.html
            text: CV
          - href: cv/publications.html
            text: Publications
      - href: R-packages.html
        text: R packages
      - href: pipeline.html
        text: Pipeline
    right:
      - text: "{{< iconify fa6-solid at title='E-mail' width=19px >}} <span id='hide-nav-item'>E-mail</span>"
        href: mailto:contact@zheer.dk
      - text: "{{< iconify fa6-brands square-github title='GitHub' width=19px >}} <span id='hide-nav-item'>GitHub</span>"
        href: https://github.com/zheer-kejlberg
      - text: "{{< iconify fa6-brands google-scholar title='Google Scholar' width=19px >}} <span id='hide-nav-item'>Google Scholar</span>"
        href: https://scholar.google.com/citations?user=Pr1jGNwAAAAJ&hl=en
      - text: "{{< iconify fa6-brands orcid title='Orcid' width=19px >}} <span id='hide-nav-item'>Orcid</span>"
        href: https://orcid.org/0000-0003-1201-199X

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    toc: true
    css: css/style.css